// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: logagent.proto

package logagentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonData      string                 `protobuf:"bytes,1,opt,name=json_data,json=jsonData,proto3" json:"json_data,omitempty"` // raw JSON string
	Pipelines     []string               `protobuf:"bytes,2,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
	ApiKey        string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_logagent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logagent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_logagent_proto_rawDescGZIP(), []int{0}
}

func (x *LogRequest) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

func (x *LogRequest) GetPipelines() []string {
	if x != nil {
		return x.Pipelines
	}
	return nil
}

func (x *LogRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_logagent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logagent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_logagent_proto_rawDescGZIP(), []int{1}
}

func (x *LogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_logagent_proto protoreflect.FileDescriptor

const file_logagent_proto_rawDesc = "" +
	"\n" +
	"\x0elogagent.proto\x12\blogagent\"`\n" +
	"\n" +
	"LogRequest\x12\x1b\n" +
	"\tjson_data\x18\x01 \x01(\tR\bjsonData\x12\x1c\n" +
	"\tpipelines\x18\x02 \x03(\tR\tpipelines\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\"A\n" +
	"\vLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2B\n" +
	"\bLogAgent\x126\n" +
	"\aSendLog\x12\x14.logagent.LogRequest\x1a\x15.logagent.LogResponseB\x1dZ\x1bdata-nadhi-agent/logagentpbb\x06proto3"

var (
	file_logagent_proto_rawDescOnce sync.Once
	file_logagent_proto_rawDescData []byte
)

func file_logagent_proto_rawDescGZIP() []byte {
	file_logagent_proto_rawDescOnce.Do(func() {
		file_logagent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logagent_proto_rawDesc), len(file_logagent_proto_rawDesc)))
	})
	return file_logagent_proto_rawDescData
}

var file_logagent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_logagent_proto_goTypes = []any{
	(*LogRequest)(nil),  // 0: logagent.LogRequest
	(*LogResponse)(nil), // 1: logagent.LogResponse
}
var file_logagent_proto_depIdxs = []int32{
	0, // 0: logagent.LogAgent.SendLog:input_type -> logagent.LogRequest
	1, // 1: logagent.LogAgent.SendLog:output_type -> logagent.LogResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_logagent_proto_init() }
func file_logagent_proto_init() {
	if File_logagent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logagent_proto_rawDesc), len(file_logagent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logagent_proto_goTypes,
		DependencyIndexes: file_logagent_proto_depIdxs,
		MessageInfos:      file_logagent_proto_msgTypes,
	}.Build()
	File_logagent_proto = out.File
	file_logagent_proto_goTypes = nil
	file_logagent_proto_depIdxs = nil
}
