// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: logagent.proto

package logagentpb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogAgent_SendLog_FullMethodName = "/logagent.LogAgent/SendLog"
)

// LogAgentClient is the client API for LogAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogAgentClient interface {
	// SDK sends one log message
	SendLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
}

type logAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewLogAgentClient(cc grpc.ClientConnInterface) LogAgentClient {
	return &logAgentClient{cc}
}

func (c *logAgentClient) SendLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, LogAgent_SendLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogAgentServer is the server API for LogAgent service.
// All implementations must embed UnimplementedLogAgentServer
// for forward compatibility.
type LogAgentServer interface {
	// SDK sends one log message
	SendLog(context.Context, *LogRequest) (*LogResponse, error)
	mustEmbedUnimplementedLogAgentServer()
}

// UnimplementedLogAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogAgentServer struct{}

func (UnimplementedLogAgentServer) SendLog(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendLog not implemented")
}
func (UnimplementedLogAgentServer) mustEmbedUnimplementedLogAgentServer() {}
func (UnimplementedLogAgentServer) testEmbeddedByValue()                  {}

// UnsafeLogAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogAgentServer will
// result in compilation errors.
type UnsafeLogAgentServer interface {
	mustEmbedUnimplementedLogAgentServer()
}

func RegisterLogAgentServer(s grpc.ServiceRegistrar, srv LogAgentServer) {
	// If the following call pancis, it indicates UnimplementedLogAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogAgent_ServiceDesc, srv)
}

func _LogAgent_SendLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogAgentServer).SendLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogAgent_SendLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogAgentServer).SendLog(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogAgent_ServiceDesc is the grpc.ServiceDesc for LogAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logagent.LogAgent",
	HandlerType: (*LogAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendLog",
			Handler:    _LogAgent_SendLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logagent.proto",
}
